### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by bobiblazeski** [Hypercubed/f-flat_node#2]
npm i

> tripwire@4.1.0 install /home/slobodan/learn/f-flat_node/node_modules/tripwire
> node install.js

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org:443
gyp ERR! stack     at Object.exports._errnoException (util.js:890:11)
gyp ERR! stack     at errnoException (dns.js:31:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
gyp ERR! System Linux 4.2.0-35-generic
gyp ERR! command "/home/slobodan/.nvm/versions/node/v5.10.1/bin/node" "/home/slobodan/.nvm/versions/node/v5.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/slobodan/learn/f-flat_node/node_modules/tripwire
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN f-flat@0.0.0 No repository field.
npm ERR! Linux 4.2.0-35-generic
npm ERR! argv "/home/slobodan/.nvm/versions/node/v5.10.1/bin/node" "/home/slobodan/.nvm/versions/node/v5.10.1/bin/npm" "i"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! tripwire@4.1.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tripwire@4.1.0 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tripwire package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tripwire
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tripwire
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/slobodan/learn/f-flat_node/npm-debug.log

**Comment by Hypercubed** [comment]
Hmmm... tripwire is a pretty low level module to try to catch infinite loops, which are possible in f-flat.  If you are comfortable digging into the code tripwire can easily be removed.  It is only used in the repl.  https://github.com/Hypercubed/f-flat_node/blob/master/bin/repl.js

Honestly , I'm not surprised you have issues... this is very much my toy.  You may be the first to try to use it.  I've recently been trying to work on the documentation:  https://github.com/Hypercubed/f-flat_node/wiki

**Comment by Hypercubed** [comment]
I"ve disabled tripwire for now.  If you were not able to do it yourself you can try again using the new master.

Thanks again for taking a look.
